import xml.etree.ElementTree as ET
import datetime


def main(xml_path: str = "coverage.xml", out_fpath: str = "COVERAGE.md"):
    """
    Args:
        xml_path: Path to coverage.xml generated by pytest-cov.
        out_fpath: Path to write coverage summary.
    """
    tree = ET.parse(xml_path)
    root = tree.getroot()

    lines_valid = int(root.attrib["lines-valid"])
    lines_covered = int(root.attrib["lines-covered"])
    percent = float(root.attrib["line-rate"]) * 100

    summary = (
        f"# Coverage\n\n"
        f"Last checked: {datetime.date.today().isoformat()}\n\n"
        f"Coverage: {lines_covered}/{lines_valid} lines ({percent:.1f}%)\n"
    )

    with open(out_fpath, "w") as f:
        f.write(summary)


if __name__ == "__main__":
    import tyro

    tyro.cli(main)
